apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sbm-business-service
  labels:
    app: sbm-business-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sbm-business-service
  template:
    metadata:
      labels:
        app: sbm-business-service
    spec:
      containers:
        - name: sbm-business-service
          image: 10.100.254.144/bjc/sbm-business-service:latest
          ports:
            - containerPort: 8084
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /hi
#              port: 8084
#            initialDelaySeconds: 5
#            timeoutSeconds: 3
#            successThreshold: 1
#            failureThreshold: 3
          imagePullPolicy: Always
          env:
            - name: ZK_IP
              value: "zk-cs"
            - name: ZK_PORT
              value: "2181"

            - name: SEATA_IP
              value: "seata-server"
            - name: SEATA_PORT
              value: "30091"

            - name: MYSQL_IP
              value: "mysql-svc"
            - name: MYSQL_PORT
              value: "30306"
            - name: MYSQL_PASSWORD
              value: "123456789"

            - name: REDIS_IP
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"

            - name: HONORIFIC
              value: "The Most Honorable"

            - name: JAVA_TOOL_OPTIONS
              value: "-Ddubbo.provider.threads=200"

---
apiVersion: v1
kind: Service
metadata:
  name: sbm-business-service
  namespace: default
  labels:
    app: sbm-business-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: sbm-business-service
  type: NodePort  